---
grails:
    profile: web
    grails:
        profiles: web
    environments:
        development:
            global:
                user:
                    photoDir: "grails-app/assets/images/user-photos"  # Path for development
        production:
            global:
                user:
                    photoDir: "/opt/tomcat/images/"  # Path for production
    codegen:
        defaultPackage: com.bitsoft.mls
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    servlet:
        multipart:
            enabled: true  # Ensure multipart support is enabled
            max-file-size: 10MB   # Adjust to the required size, e.g., 10MB
            max-request-size: 10MB # Adjust to the required size
            file-size-threshold: 2MB # Threshold for writing files to disk, adjust as needed
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        upload:
            maxFileSize: 2000000
            maxRequestSize: 2000000
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

logging:
    level:
        org.springframework.web.multipart: DEBUG
grails:
    cors:
        enabled: true